# Generated by Django 4.2.11 on 2024-04-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherInfoRequired",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maxWindSpeed", models.DecimalField(decimal_places=2, max_digits=10)),
                ("feelsLike", models.DecimalField(decimal_places=2, max_digits=10)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=10)),
                ("humidity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("pressure", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rainfall", models.IntegerField()),
                ("rainRate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "solarRadiation",
                    models.DecimalField(decimal_places=3, max_digits=10),
                ),
                ("hStability", models.IntegerField()),
                ("vStability", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="corridorHalfAngle",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="feelsLike",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="humidity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="maxWindSpeed",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="pressure",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="rainRate",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="rainRateEstimated",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="scalarWindDirection",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="scalarWindSpeed",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="sigmaTheta",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="temperature",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="uComponent",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="vComponent",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="windDirection",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="weatherinfo",
            name="windSpeed",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
