# Generated by Django 4.2.11 on 2024-04-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherApp", "0002_weatherinforequired_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherinforequired",
            name="maxWindSpeed",
        ),
        migrations.AlterField(
            model_name="weatherinforequired",
            name="feelsLike",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="weatherinforequired",
            name="hStability",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="weatherinforequired",
            name="humidity",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="weatherinforequired",
            name="pressure",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="weatherinforequired",
            name="rainRate",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="weatherinforequired",
            name="rainfall",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="weatherinforequired",
            name="solarRadiation",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="weatherinforequired",
            name="temperature",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="weatherinforequired",
            name="vStability",
            field=models.IntegerField(null=True),
        ),
    ]
